// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Carrito struct {
	IDCarrito int32         `json:"id_carrito"`
	IDUsuario sql.NullInt32 `json:"id_usuario"`
	Total     string        `json:"total"`
}

type Producto struct {
	IDProducto      int32          `json:"id_producto"`
	NombreProd      string         `json:"nombre_prod"`
	DescripcionProd sql.NullString `json:"descripcion_prod"`
	PrecioProd      string         `json:"precio_prod"`
	StockProd       int32          `json:"stock_prod"`
	Categoria       string         `json:"categoria"`
}

type ProductosCarrito struct {
	IDProductosCarrito int32 `json:"id_productos_carrito"`
	IDProducto         int32 `json:"id_producto"`
	IDCarrito          int32 `json:"id_carrito"`
	Cantidad           int32 `json:"cantidad"`
}

type Usuario struct {
	IDUsuario  int32  `json:"id_usuario"`
	Email      string `json:"email"`
	Contrasena string `json:"contrasena"`
}
