// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const createCarrito = `-- name: CreateCarrito :one
INSERT INTO carrito (id_usuario, total)
VALUES ($1, $2)
RETURNING id_carrito, id_usuario, total
`

type CreateCarritoParams struct {
	IDUsuario sql.NullInt32 `json:"id_usuario"`
	Total     string        `json:"total"`
}

// CONSULTAS PARA LA ENTIDAD: CARRITO-----------------------------------------------------------------
func (q *Queries) CreateCarrito(ctx context.Context, arg CreateCarritoParams) (Carrito, error) {
	row := q.db.QueryRowContext(ctx, createCarrito, arg.IDUsuario, arg.Total)
	var i Carrito
	err := row.Scan(&i.IDCarrito, &i.IDUsuario, &i.Total)
	return i, err
}

const createProducto = `-- name: CreateProducto :one
INSERT INTO producto (nombre_prod, descripcion_prod, precio_prod, stock_prod, categoria)
VALUES ($1, $2, $3, $4, $5)
RETURNING id_producto, nombre_prod, descripcion_prod, precio_prod, stock_prod, categoria
`

type CreateProductoParams struct {
	NombreProd      string         `json:"nombre_prod"`
	DescripcionProd sql.NullString `json:"descripcion_prod"`
	PrecioProd      string         `json:"precio_prod"`
	StockProd       int32          `json:"stock_prod"`
	Categoria       string         `json:"categoria"`
}

// CONSULTAS PARA LA ENTIDAD: PRODUCTO--------------------------------------------------------
func (q *Queries) CreateProducto(ctx context.Context, arg CreateProductoParams) (Producto, error) {
	row := q.db.QueryRowContext(ctx, createProducto,
		arg.NombreProd,
		arg.DescripcionProd,
		arg.PrecioProd,
		arg.StockProd,
		arg.Categoria,
	)
	var i Producto
	err := row.Scan(
		&i.IDProducto,
		&i.NombreProd,
		&i.DescripcionProd,
		&i.PrecioProd,
		&i.StockProd,
		&i.Categoria,
	)
	return i, err
}

const createUsuario = `-- name: CreateUsuario :one
INSERT INTO usuario (email, contrasena)
VALUES ($1, $2)
RETURNING id_usuario, email, contrasena
`

type CreateUsuarioParams struct {
	Email      string `json:"email"`
	Contrasena string `json:"contrasena"`
}

// CONSULTAS PARA LA ENTIDAD: USUARIO-----------------------------------------------------
func (q *Queries) CreateUsuario(ctx context.Context, arg CreateUsuarioParams) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, createUsuario, arg.Email, arg.Contrasena)
	var i Usuario
	err := row.Scan(&i.IDUsuario, &i.Email, &i.Contrasena)
	return i, err
}

const deleteCarrito = `-- name: DeleteCarrito :exec
DELETE FROM carrito
WHERE id_carrito = $1
`

func (q *Queries) DeleteCarrito(ctx context.Context, idCarrito int32) error {
	_, err := q.db.ExecContext(ctx, deleteCarrito, idCarrito)
	return err
}

const deleteProducto = `-- name: DeleteProducto :exec
DELETE FROM producto
WHERE id_producto = $1
`

func (q *Queries) DeleteProducto(ctx context.Context, idProducto int32) error {
	_, err := q.db.ExecContext(ctx, deleteProducto, idProducto)
	return err
}

const deleteUsuario = `-- name: DeleteUsuario :exec
DELETE FROM usuario
WHERE id_usuario = $1
`

func (q *Queries) DeleteUsuario(ctx context.Context, idUsuario int32) error {
	_, err := q.db.ExecContext(ctx, deleteUsuario, idUsuario)
	return err
}

const getCarrito = `-- name: GetCarrito :one
SELECT id_carrito, id_usuario, total
FROM carrito
WHERE id_carrito = $1
`

func (q *Queries) GetCarrito(ctx context.Context, idCarrito int32) (Carrito, error) {
	row := q.db.QueryRowContext(ctx, getCarrito, idCarrito)
	var i Carrito
	err := row.Scan(&i.IDCarrito, &i.IDUsuario, &i.Total)
	return i, err
}

const getProducto = `-- name: GetProducto :one
SELECT id_producto, nombre_prod, descripcion_prod, precio_prod, stock_prod, categoria
FROM producto
WHERE id_producto = $1
`

func (q *Queries) GetProducto(ctx context.Context, idProducto int32) (Producto, error) {
	row := q.db.QueryRowContext(ctx, getProducto, idProducto)
	var i Producto
	err := row.Scan(
		&i.IDProducto,
		&i.NombreProd,
		&i.DescripcionProd,
		&i.PrecioProd,
		&i.StockProd,
		&i.Categoria,
	)
	return i, err
}

const getUsuario = `-- name: GetUsuario :one
SELECT id_usuario, email, contrasena
FROM usuario
WHERE id_usuario = $1
`

func (q *Queries) GetUsuario(ctx context.Context, idUsuario int32) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, getUsuario, idUsuario)
	var i Usuario
	err := row.Scan(&i.IDUsuario, &i.Email, &i.Contrasena)
	return i, err
}

const getUsuarioByEmail = `-- name: GetUsuarioByEmail :one
SELECT id_usuario, email, contrasena
FROM usuario
WHERE email = $1
`

func (q *Queries) GetUsuarioByEmail(ctx context.Context, email string) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, getUsuarioByEmail, email)
	var i Usuario
	err := row.Scan(&i.IDUsuario, &i.Email, &i.Contrasena)
	return i, err
}

const listCarritos = `-- name: ListCarritos :many
SELECT id_carrito, id_usuario, total
FROM carrito
ORDER BY id_carrito
`

func (q *Queries) ListCarritos(ctx context.Context) ([]Carrito, error) {
	rows, err := q.db.QueryContext(ctx, listCarritos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Carrito
	for rows.Next() {
		var i Carrito
		if err := rows.Scan(&i.IDCarrito, &i.IDUsuario, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductos = `-- name: ListProductos :many
SELECT id_producto, nombre_prod, descripcion_prod, precio_prod, stock_prod, categoria
FROM producto
ORDER BY id_producto
`

func (q *Queries) ListProductos(ctx context.Context) ([]Producto, error) {
	rows, err := q.db.QueryContext(ctx, listProductos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Producto
	for rows.Next() {
		var i Producto
		if err := rows.Scan(
			&i.IDProducto,
			&i.NombreProd,
			&i.DescripcionProd,
			&i.PrecioProd,
			&i.StockProd,
			&i.Categoria,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCarrito = `-- name: UpdateCarrito :exec
UPDATE carrito
SET id_usuario = $2,
    total = $3
WHERE id_carrito = $1
`

type UpdateCarritoParams struct {
	IDCarrito int32         `json:"id_carrito"`
	IDUsuario sql.NullInt32 `json:"id_usuario"`
	Total     string        `json:"total"`
}

func (q *Queries) UpdateCarrito(ctx context.Context, arg UpdateCarritoParams) error {
	_, err := q.db.ExecContext(ctx, updateCarrito, arg.IDCarrito, arg.IDUsuario, arg.Total)
	return err
}

const updateProducto = `-- name: UpdateProducto :exec
UPDATE producto
SET nombre_prod = $2,
    descripcion_prod = $3,
    precio_prod = $4,
    stock_prod = $5,
    categoria = $6
WHERE id_producto = $1
`

type UpdateProductoParams struct {
	IDProducto      int32          `json:"id_producto"`
	NombreProd      string         `json:"nombre_prod"`
	DescripcionProd sql.NullString `json:"descripcion_prod"`
	PrecioProd      string         `json:"precio_prod"`
	StockProd       int32          `json:"stock_prod"`
	Categoria       string         `json:"categoria"`
}

func (q *Queries) UpdateProducto(ctx context.Context, arg UpdateProductoParams) error {
	_, err := q.db.ExecContext(ctx, updateProducto,
		arg.IDProducto,
		arg.NombreProd,
		arg.DescripcionProd,
		arg.PrecioProd,
		arg.StockProd,
		arg.Categoria,
	)
	return err
}
